---
# deliver.yml: playbook file for ansible

- name: "Deliver"
  hosts: all
  tasks:
    - set_fact:
        cdn_path : "{{ cdn_directory }}/{{ env }}/{{ version }}"
    - name: "Make Directory"
      file:
        path: "/var/opt/docker/volumes/cdn_nginx_www/_data/{{ cdn_path }}"
        state: directory
        recurse: yes
        mode: '0755'
    - name: "Synchronize Content"
      synchronize:
        src: build/
        dest: "/var/opt/docker/volumes/cdn_nginx_www/_data/{{ cdn_path }}"
        archive: no
        recursive: yes
        times: no
        checksum: yes
        delete: yes
...
