---
# deliver.yml: playbook file for ansible

- name: "Deliver"
  hosts: all
  tasks:
    - name: "Include Vars"
      include_vars:
        name: configuration
        file: public/override/configuration.json
    - name: "Debug Vars"
      debug:
        msg: "{{ configuration.application }}"
    - name: "Make Directory"
      file:
        path: "/var/opt/docker/volumes/cdn_nginx_www/_data/{{ configuration.application.directory | default('master/')}}"
        state: directory
        recurse: yes
        mode: '0755'
    - name: "Synchronize Content"
      synchronize:
        src: build/
        dest: "/var/opt/docker/volumes/cdn_nginx_www/_data/{{ configuration.application.directory | default('master/') }}"
        archive: no
        recursive: yes
        times: no
        checksum: yes
        delete: yes
        private_key: .ssh/id_ed25519
...
