---
# hosts.yml: inventory file for ansible

all:
  vars:
    ansible_port: 558
    ansible_user: dydu
    ansible_ssh_common_args: '-i .ssh/id_ed25519 -o StrictHostKeyChecking=no'
  hosts:
    node1.cdn.dydu-priv.com:
    node2.cdn.dydu-priv.com:
...
