---
# hosts.yml: inventory file for ansible

all:
  vars:
    ansible_port: 558
    ansible_user: dydu
  children:
    project:
      hosts:
        node1.cdn.dydu-priv.com:
        node2.cdn.dydu-priv.com:
        node3.cdn.dydu-priv.com:
      vars:
        ansible_ssh_common_args: '-i .ssh/id_ed25519 -o StrictHostKeyChecking=no'
    uat:
      hosts:
        uat1.cdn.dydu-priv.com:
      vars:
        cdn_directory: "dydubox/configurations/demo"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    prod:
      hosts:
        node1.cdn.dydu-priv.com:
        node2.cdn.dydu-priv.com:
        node3.cdn.dydu-priv.com:
      vars:
        cdn_directory: "dydubox/configurations/demo"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
...
