---
# hosts.yml: inventory file for ansible

all:
  vars:
    ansible_port: 558
    ansible_user: dydu
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    cdn_directory: "dydubox/configurations/demo"
  children:
    uat:
      hosts:
        uat1.cdn.dydu-priv.com:
    prod:
      hosts:
        node1.cdn.dydu-priv.com:
        node2.cdn.dydu-priv.com:
        node3.cdn.dydu-priv.com:
...
